# notification-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: pagadis/notification-service:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 5002
      targetPort: 5002