# payment-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: pagadis/payment-service:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 5001
      targetPort: 5001